from fastapi import APIRouter
from app.api.v1.endpoints import appointments, customers, services, auth, plans, service_templates, salons, sub_services, users, files, customization, subscriptions, dashboard, superadmin, superadmin_settings, activity_logs, products, product_categories, cart, orders, customer_auth, packs, wallet, withdrawals, support, complaints, reviews, market, special_requests, showroom, notifications, media, favorites, faq, customer_support, chat, chat_websocket

api_router = APIRouter()

api_router.include_router(auth.router, prefix="/auth", tags=["authentication"])
api_router.include_router(customer_auth.router, prefix="/customer-auth", tags=["customer-authentication"])
api_router.include_router(chat.router, prefix="/chat", tags=["chat"])
api_router.include_router(chat_websocket.router, prefix="/chat", tags=["chat-websocket"])
api_router.include_router(favorites.router, prefix="/favorites", tags=["favorites"])
api_router.include_router(market.router, prefix="/market", tags=["market"])
api_router.include_router(showroom.router, prefix="/showroom", tags=["showroom"])
api_router.include_router(dashboard.router, prefix="/dashboard", tags=["dashboard"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(media.router, prefix="/media", tags=["media"])
api_router.include_router(faq.router, prefix="/faq", tags=["faq"])
api_router.include_router(customer_support.router, prefix="/customer-support", tags=["customer-support"])
api_router.include_router(plans.router, prefix="/plans", tags=["plans"])
api_router.include_router(service_templates.router, prefix="/service-templates", tags=["service-templates"])
api_router.include_router(salons.router, prefix="/salons", tags=["salons"])
api_router.include_router(appointments.router, prefix="/appointments", tags=["appointments"])
api_router.include_router(special_requests.router, prefix="/special-requests", tags=["special-requests"])
api_router.include_router(customers.router, prefix="/customers", tags=["customers"])
api_router.include_router(services.router, prefix="/services", tags=["services"])
api_router.include_router(sub_services.router, prefix="/sub-services", tags=["sub-services"])
api_router.include_router(products.router, prefix="/products", tags=["products"])
api_router.include_router(product_categories.router, prefix="/product-categories", tags=["product-categories"])
api_router.include_router(packs.router, prefix="/packs", tags=["packs"])
api_router.include_router(cart.router, prefix="/cart", tags=["cart"])
api_router.include_router(orders.router, prefix="/orders", tags=["orders"])
api_router.include_router(wallet.router, prefix="/wallet", tags=["wallet"])
api_router.include_router(withdrawals.router, prefix="/withdrawals", tags=["withdrawals"])
api_router.include_router(support.router, prefix="/support", tags=["support"])
api_router.include_router(complaints.router, prefix="/complaints", tags=["complaints"])
api_router.include_router(reviews.router, prefix="/reviews", tags=["reviews"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(files.router, prefix="/files", tags=["files"])
api_router.include_router(customization.router, prefix="/customization", tags=["customization"])
api_router.include_router(subscriptions.router, prefix="/subscriptions", tags=["subscriptions"])
api_router.include_router(activity_logs.router, prefix="/activity-logs", tags=["activity-logs"])
api_router.include_router(superadmin.router, prefix="/superadmin/salons", tags=["superadmin"])
api_router.include_router(superadmin_settings.router, prefix="/superadmin/settings", tags=["superadmin-settings"])
